### PR TITLE
Important security fix + other compliance and improvement fixes

### PR DESCRIPTION
**Pull request by omarbenhamid**
Most importantly the removal X-File-Name header which allowed attacker to read any file accessible to django via webdav.

### CODE REVIEW

**Comment by anx-ckreuzberger** [comment]
Thank you very much for your pull request!

Disclaimer:
As I have only forked the original work from TZanke/djangodav, and my knowledge of the webdav protocol is very rudimentary, I can not easily and immediately confirm if any of the changes you propose are according to the webdav protocol. But I'm going to assume that you know what you are doing +1

Out of curiosity: do you have any webdav clients that are you testing this library with, that require those changes? I love to keep a list of compatible clients (webdav client support is very very vendor specific, especially for Windows systems).

I do like the changes with the content-range, is there a webdav client that I can test these changes with (Linux, Windows, Mac)? As far as I can see this is only for writing, not for reading?

The fix for "RFC 2616: HEAD method must not return a message body" seems fine. I'm not sure if this is implemented for all endpoints at any time, but we will see.

About the x-file-name header: I'm not sure how this poses a security risk, but I'll take a look at it. I believe I added this header because it is implemented by Apache or nginx. I'll double check with my [example app](https://github.com/anx-ckreuzberger/djangodav-example-app).

**Comment by omarbenhamid** [comment]
Hi Christian,
I thank you for maintaining this code. I currently use the range header through Java 's java.net.HttpURLConnection Client library. I don't know of other clients using range header for upload.

For security issue : if you pass the path of any file on server (ex. settings.py) to x-file-name header, it will be copied as a  webdav ressource that you can download, this way you can download arbitrary files on the webdav server.

**Comment by anx-ckreuzberger** [comment]
Thanks for the note!
I haven't forgotten about this issue, I will check it out asap.

**Comment by anx-ckreuzberger** [comment]
Hi,

sorry again for not handling this PR.

I've beeng looking at your commits, and the part with 
```python
        # check headers for X-File-Name
        file_name_forwarding = request.META.get('HTTP_X_FILE_NAME', None)
        if file_name_forwarding:
            self.resource.write(request, file_name_forwarding)
        else:
            self.resource.write(request)
```

is there for a reason. I'm using the `HTTP_X_FILE_NAME` to ensure that one can upload files via nginx or Apache, rather than Django, to improve performance. I have an example nginx config here:

https://github.com/anx-ckreuzberger/djangodav-example-app/blob/75af0115dcbdb795efeefd6b9b45f8c2787d4a52/docker/nginx/django.conf#L39-L56

https://github.com/anx-ckreuzberger/djangodav-example-app/blob/75af0115dcbdb795efeefd6b9b45f8c2787d4a52/docker/nginx/django.conf#L92-L113

This sets the `X-File-Name` header when uploading a file. Ofcourse this is a security issue, the header needs to be checked (or a configurable setting needs to be used). We already have those two:
```python
DJANGODAV_X_REDIRECT = getattr(settings, 'DJANGODAV_X_REDIRECT', None)
DJANGODAV_X_REDIRECT_PREFIX = getattr(settings, 'DJANGODAV_X_REDIRECT_PREFIX', "")

```
I'll accept the PR for now, and I'll add another setting here that enables this behaviour.

Thank you very much for discovering and fixing this issue.

**Pull request merged**
